"""Write `n` attacked rows around one replay out as a C header, for the firmware to read.

    python3 -m board.rows "data/part_*/*.csv" out n

The rows are the scaled ones `evaluate.pc.run` scores, built from the logs the way it
builds them. `out` only saves building them again. Each float is written as its float32
bits in hex, so the board reads exactly those values.
"""

from __future__ import annotations

import glob
import os
import sys

import numpy as np

from assemble.split import split
from common.dataset import arrays_for, attacks_for, seconds_for
from common.settings import Settings

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, "application", "rows", "rows.h")


def window(first, last, total, n):
    """`n` rows with rows `first` to `last` in the middle, as a slice of `total` rows."""
    start = min(max((first + last + 1 - n) // 2, 0), total - n)
    return slice(start, start + n)


def bits(rows):
    """Each float32 of `rows` as its bits, `0x` and eight hex digits."""
    words = np.ascontiguousarray(rows, dtype=np.float32).view(np.uint32)
    return [[f"0x{w:08x}" for w in row] for row in words.tolist()]


def header(rows, source):
    """The C header holding `rows` as float32 bits, with where they came from."""
    lines = [f"/* {source} */",
             "#include <stdint.h>",
             "",
             f"#define ROWS\t\t{len(rows)}",
             f"#define SIGNALS\t{rows.shape[1]}",
             "",
             "static const uint32_t rows[ROWS][SIGNALS] = {"]
    lines += [f"\t{{{', '.join(row)}}}," for row in bits(rows)]
    lines += ["};", ""]
    return "\n".join(lines)


def main(pattern, out_dir, n):
    settings = Settings()
    os.makedirs(out_dir, exist_ok=True)
    logs = sorted(glob.glob(pattern))
    train_logs, test_logs = split(seconds_for(logs, out_dir, settings), settings.TRAIN)
    data, _ = arrays_for(train_logs, out_dir, settings)
    # the same attacked rows as evaluate.pc.run
    got, _ = attacks_for(train_logs, test_logs, data["scale"], out_dir, settings)
    attacks, rows = got["attacks"], got["rows"]
    # the first replay that moved a row far enough to count as an anomaly
    i, attack = next((i, a) for i, a in enumerate(attacks)
                     if a["moved"] >= settings.MOVED)
    at = window(attack["first"], attack["last"], len(rows), n)
    source = (f"generated by board/rows.py: attacked rows {at.start} to {at.stop - 1}, "
              f"around attack {i} at rows {attack['first']} to {attack['last']}")
    os.makedirs(os.path.dirname(HEADER), exist_ok=True)
    with open(HEADER, "w") as f:
        f.write(header(rows[at], source))
    print(source)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], int(sys.argv[3]))
