#ifndef BOARD_SIGNALS_H
#define BOARD_SIGNALS_H

/* SIGNALS in preprocess/features/signal_state.py, the columns of a row. */
#define SIGNAL_COUNT 17

#define SIGNAL_ENGINE_SPEED 0
#define SIGNAL_DRIVER_DEMAND_TORQUE 1
#define SIGNAL_ACTUAL_ENGINE_TORQUE 2
#define SIGNAL_ACCEL_PEDAL 3
#define SIGNAL_ENGINE_LOAD 4
#define SIGNAL_WHEEL_SPEED 5
#define SIGNAL_FUEL_RATE 6
#define SIGNAL_OUTPUT_SHAFT_SPEED 7
#define SIGNAL_CLUTCH_SLIP 8
#define SIGNAL_INPUT_SHAFT_SPEED 9
#define SIGNAL_SELECTED_GEAR 10
#define SIGNAL_CURRENT_GEAR 11
#define SIGNAL_TACHOGRAPH_SPEED 12
#define SIGNAL_BRAKE_PEDAL 13
#define SIGNAL_STEERING_ANGLE 14
#define SIGNAL_YAW_RATE 15
#define SIGNAL_LATERAL_ACCEL 16

#endif
